export const ACTION_TYPES = {
  READ_ALL_DATA: "READ_ALL_DATA",
  READ_ONE_DATA: "READ_ONE_DATA",
  CREATE_DATA: "CREATE_DATA",
  UPDATE_DATA: "UPDATE_DATA",
  DELETE_DATA: "DELETE_DATA",
  NO_DATA: "NO_DATA"
};
